using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DPokemonSystem : MonoBehaviour
{
    public class PokeInfo{
        public string pokeId;
        public string pokeName;
        public string type1;
        public string type2;
        public PokeInfo(string id, string pkname, string type1, string type2)
        {
            this.pokeId = id;
            this.pokeName = pkname;
            this.type1 = type1;
            this.type2 = type2;
        }
    }

    public Dictionary<string, PokeInfo> dict;
    public Dictionary<string, int> dictType;
    private float[][] board; //effectiveness

    public DStat LoadStat(int pokeId, bool isShiny, bool isAlola)
    {
        string num3 = "";
        if (pokeId < 10)
            num3 = "00" + pokeId.ToString();
        else if (pokeId < 100)
            num3 = "0" + pokeId.ToString();
        else
            num3 = pokeId.ToString();

        // Load stat
        DStat stat = new DStat();

        PokeInfo pokeInfo;

        try {
            if (isAlola)
                pokeInfo = dict[num3 + "alola"];
            else
                pokeInfo = dict[num3];
        }
        catch {
            //pokeInfo = dict[num3];
            Debug.LogError("Error loading at num3 = " + num3.ToString());
            return stat;
        }

        stat.characterName = pokeInfo.pokeName;
        stat.type1 = pokeInfo.type1;
        stat.type2 = pokeInfo.type2;

        if (isShiny)
            num3 += "s";
        Sprite[] sprites;
        if (isAlola)
        {
            sprites = Resources.LoadAll<Sprite>(num3 + "_1");
            if (sprites.Length == 0)
                sprites = Resources.LoadAll<Sprite>(num3);
        }
        else
            sprites = Resources.LoadAll<Sprite>(num3);

        //if (isShiny)
        //    sprites = Resources.LoadAll<Sprite>(num3 + "s");
        //else
        //    sprites = Resources.LoadAll<Sprite>(num3);

        Sprite down1 = sprites[0];
        Sprite down2 = sprites[1];
        Sprite down3 = sprites[2];
        Sprite down4 = sprites[3];

        Sprite left1 = sprites[4];
        Sprite left2 = sprites[5];
        Sprite left3 = sprites[6];
        Sprite left4 = sprites[7];

        Sprite right1 = sprites[8];
        Sprite right2 = sprites[9];
        Sprite right3 = sprites[10];
        Sprite right4 = sprites[11];

        Sprite up1 = sprites[12];
        Sprite up2 = sprites[13];
        Sprite up3 = sprites[14];
        Sprite up4 = sprites[15];

        //Sprite up1 = Resources.Load<Sprite>("pokeup1 (" + pokeId + ")");
        //Sprite up2 = Resources.Load<Sprite>("pokeup2 (" + pokeId + ")");

        //Sprite down1 = Resources.Load<Sprite>("pokedown1 (" + pokeId + ")");
        //Sprite down2 = Resources.Load<Sprite>("pokedown2 (" + pokeId + ")");

        //Sprite left1 = Resources.Load<Sprite>("pokeleft1 (" + pokeId + ")");
        //Sprite left2 = Resources.Load<Sprite>("pokeleft2 (" + pokeId + ")");

        //Sprite right1 = Resources.Load<Sprite>("pokeright1 (" + pokeId + ")");
        //Sprite right2 = Resources.Load<Sprite>("pokeright2 (" + pokeId + ")");

        stat.stand_up = new Sprite[] { up1 };
        stat.stand_down = new Sprite[] { down1 };
        stat.stand_left = new Sprite[] { left1 };
        stat.stand_right = new Sprite[] { right1 };

        stat.go_up = new Sprite[] { up1, up2, up3, up4 };
        stat.go_down = new Sprite[] { down1, down2, down3, down4 };
        stat.go_left = new Sprite[] { left1, left2, left3, left4 };
        stat.go_right = new Sprite[] { right1, right2, right3, right4 };

        stat.run_up = new Sprite[] { up1, up2, up3, up4 };
        stat.run_down = new Sprite[] { down1, down2, down3, down4 };
        stat.run_left = new Sprite[] { left1, left2, left3, left4 };
        stat.run_right = new Sprite[] { right1, right2, right3, right4 };

        stat.attack_up = new Sprite[] { up1, up2, up3, up4 };
        stat.attack_down = new Sprite[] { down1, down2, down3, down4 };
        stat.attack_left = new Sprite[] { left1, left2, left3, left4 };
        stat.attack_right = new Sprite[] { right1, right2, right3, right4 };

        stat.speed = 0.7f;
        stat.attackObjectName = "Attack";
        stat.attackRange = 0.2f;

        return stat;
    }

    public float CalculateReceiveDame(DHitParam hitParam, DStat pokeStat)
    {
        int hitType1 = dictType[hitParam.type1];
        int hitType2 = dictType[hitParam.type2];
        int selfType1 = dictType[pokeStat.type1];
        int selfType2 = dictType[pokeStat.type2];

        float multiple = 1;

        if (hitType1 != 18 && selfType1 != 18)
            multiple *= board[hitType1][selfType1];

        if (hitType1 != 18 && selfType2 != 18)
            multiple *= board[hitType1][selfType2];

        if (hitType2 != 18 && selfType1 != 18)
            multiple *= board[hitType2][selfType1];

        if (hitType2 != 18 && selfType2 != 18)
            multiple *= board[hitType2][selfType2];

        return hitParam.dame * multiple;
    }

    private void Awake()
    {
        dictType = new Dictionary<string, int>();

        dictType.Add("Normal", 0);
        dictType.Add("Fighting", 1);
        dictType.Add("Flying", 2);
        dictType.Add("Poison", 3);
        dictType.Add("Ground", 4);
        dictType.Add("Rock", 5);
        dictType.Add("Bug", 6);
        dictType.Add("Ghost", 7);
        dictType.Add("Steel", 8);
        dictType.Add("Fire", 9);
        dictType.Add("Water", 10);
        dictType.Add("Grass", 11);
        dictType.Add("Electric", 12);
        dictType.Add("Psychic", 13);
        dictType.Add("Ice", 14);
        dictType.Add("Dragon", 15);
        dictType.Add("Dark", 16);
        dictType.Add("Fairy", 17);
        dictType.Add("None", 18);

        board = new float[18][];
        board[0] = new float[] { 1, 1, 1, 1, 1, 0.5f, 1, 0, 0.5f, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
        board[1] = new float[] { 2, 1, 0.5f, 0.5f, 1, 2, 0.5f, 0, 2, 1, 1, 1, 1, 0.5f, 2, 1, 2, 0.5f };
        board[2] = new float[] { 1, 2, 1, 1, 1, 0.5f, 2, 1, 0.5f, 1, 1, 2, 0.5f, 1, 1, 1, 1, 1 };
        board[3] = new float[] { 1, 1, 1, 0.5f, 0.5f, 0.5f, 1, 0.5f, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2 };
        board[4] = new float[] { 1, 1, 0, 2, 1, 2, 0.5f, 1, 2, 2, 1, 0.5f, 2, 1, 1, 1, 1, 1 };
        board[5] = new float[] { 1, 0.5f, 2, 1, 0.5f, 1, 2, 1, 0.5f, 2, 1, 1, 1, 1, 2, 1, 1, 1 };
        board[6] = new float[] { 1, 0.5f, 0.5f, 0.5f, 1, 1, 1, 0.5f, 0.5f, 0.5f, 1, 2, 1, 2, 1, 1, 2, 0.5f };
        board[7] = new float[] { 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0.5f, 1 };
        board[8] = new float[] { 1, 1, 1, 1, 1, 2, 1, 1, 0.5f, 0.5f, 0.5f, 1, 0.5f, 1, 2, 1, 1, 2 };
        board[9] = new float[] { 1, 1, 1, 1, 1, 0.5f, 2, 1, 2, 0.5f, 0.5f, 2, 1, 1, 2, 0.5f, 1, 1 };
        board[10] = new float[] { 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 0.5f, 0.5f, 1, 1, 1, 0.5f, 1, 1 };
        board[11] = new float[] { 1, 1, 0.5f, 0.5f, 2, 2, 0.5f, 1, 0.5f, 0.5f, 2, 0.5f, 1, 1, 1, 0.5f, 1, 1 };
        board[12] = new float[] { 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0.5f, 0.5f, 1, 1, 0.5f, 1, 1 };
        board[13] = new float[] { 1, 2, 1, 2, 1, 1, 1, 1, 0.5f, 1, 1, 1, 1, 0.5f, 1, 1, 0, 1 };
        board[14] = new float[] { 1, 1, 2, 1, 2, 1, 1, 1, 0.5f, 0.5f, 0.5f, 2, 1, 1, 0.5f, 2, 1, 1 };
        board[15] = new float[] { 1, 1, 1, 1, 1, 1, 1, 1, 0.5f, 1, 1, 1, 1, 1, 1, 2, 1, 0 };
        board[16] = new float[] { 1, 0.5f, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0.5f, 0.5f };
        board[17] = new float[] { 1, 2, 1, 0.5f, 1, 1, 1, 1, 0.5f, 0.5f, 1, 1, 1, 1, 1, 2, 2, 1 };

        dict = new Dictionary<string, PokeInfo>();

        dict.Add("001", new PokeInfo("001", "Bulbasaur", "Grass", "Poison"));
        dict.Add("002", new PokeInfo("002", "Ivysaur", "Grass", "Poison"));
        dict.Add("003", new PokeInfo("003", "Venusaur", "Grass", "Poison"));
        dict.Add("004", new PokeInfo("004", "Charmander", "Fire", "None"));
        dict.Add("005", new PokeInfo("005", "Charmeleon", "Fire", "None"));
        dict.Add("006", new PokeInfo("006", "Charizard", "Fire", "Flying"));
        dict.Add("007", new PokeInfo("007", "Squirtle", "Water", "None"));
        dict.Add("008", new PokeInfo("008", "Wartortle", "Water", "None"));
        dict.Add("009", new PokeInfo("009", "Blastoise", "Water", "None"));
        dict.Add("010", new PokeInfo("010", "Caterpie", "Bug", "None"));
        dict.Add("011", new PokeInfo("011", "Metapod", "Bug", "None"));
        dict.Add("012", new PokeInfo("012", "Butterfree", "Bug", "Flying"));
        dict.Add("013", new PokeInfo("013", "Weedle", "Bug", "Poison"));
        dict.Add("014", new PokeInfo("014", "Kakuna", "Bug", "Poison"));
        dict.Add("015", new PokeInfo("015", "Beedrill", "Bug", "Poison"));
        dict.Add("016", new PokeInfo("016", "Pidgey", "Normal", "Flying"));
        dict.Add("017", new PokeInfo("017", "Pidgeotto", "Normal", "Flying"));
        dict.Add("018", new PokeInfo("018", "Pidgeot", "Normal", "Flying"));
        dict.Add("019", new PokeInfo("019", "Rattata", "Normal", "None"));
        dict.Add("019alola", new PokeInfo("019alola", "Rattata", "Dark", "Normal"));
        dict.Add("020", new PokeInfo("020", "Raticate", "Normal", "None"));
        dict.Add("020alola", new PokeInfo("020alola", "Raticate", "Dark", "Normal"));
        dict.Add("021", new PokeInfo("021", "Spearow", "Normal", "Flying"));
        dict.Add("022", new PokeInfo("022", "Fearow", "Normal", "Flying"));
        dict.Add("023", new PokeInfo("023", "Ekans", "Poison", "None"));
        dict.Add("024", new PokeInfo("024", "Arbok", "Poison", "None"));
        dict.Add("025", new PokeInfo("025", "Pikachu", "Electric", "None"));
        dict.Add("026", new PokeInfo("026", "Raichu", "Electric", "None"));
        dict.Add("026alola", new PokeInfo("026alola", "Raichu", "Electric", "Psychic"));
        dict.Add("027", new PokeInfo("027", "Sandshrew", "Ground", "None"));
        dict.Add("027alola", new PokeInfo("027alola", "Sandshrew", "Ice", "Steel"));
        dict.Add("028", new PokeInfo("028", "Sandslash", "Ground", "None"));
        dict.Add("028alola", new PokeInfo("028alola", "Sandslash", "Ice", "Steel"));
        dict.Add("029", new PokeInfo("029", "Nidoran♀", "Poison", "None"));
        dict.Add("030", new PokeInfo("030", "Nidorina", "Poison", "None"));
        dict.Add("031", new PokeInfo("031", "Nidoqueen", "Poison", "Ground"));
        dict.Add("032", new PokeInfo("032", "Nidoran♂", "Poison", "None"));
        dict.Add("033", new PokeInfo("033", "Nidorino", "Poison", "None"));
        dict.Add("034", new PokeInfo("034", "Nidoking", "Poison", "Ground"));
        dict.Add("035", new PokeInfo("035", "Clefairy", "Fairy", "None"));
        dict.Add("036", new PokeInfo("036", "Clefable", "Fairy", "None"));
        dict.Add("037", new PokeInfo("037", "Vulpix", "Fire", "None"));
        dict.Add("037alola", new PokeInfo("037alola", "Vulpix", "Ice", "None"));
        dict.Add("038", new PokeInfo("038", "Ninetales", "Fire", "None"));
        dict.Add("038alola", new PokeInfo("038alola", "Ninetales", "Ice", "Fairy"));
        dict.Add("039", new PokeInfo("039", "Jigglypuff", "Normal", "Fairy"));
        dict.Add("040", new PokeInfo("040", "Wigglytuff", "Normal", "Fairy"));
        dict.Add("041", new PokeInfo("041", "Zubat", "Poison", "Flying"));
        dict.Add("042", new PokeInfo("042", "Golbat", "Poison", "Flying"));
        dict.Add("043", new PokeInfo("043", "Oddish", "Grass", "Poison"));
        dict.Add("044", new PokeInfo("044", "Gloom", "Grass", "Poison"));
        dict.Add("045", new PokeInfo("045", "Vileplume", "Grass", "Poison"));
        dict.Add("046", new PokeInfo("046", "Paras", "Bug", "Grass"));
        dict.Add("047", new PokeInfo("047", "Parasect", "Bug", "Grass"));
        dict.Add("048", new PokeInfo("048", "Venonat", "Bug", "Poison"));
        dict.Add("049", new PokeInfo("049", "Venomoth", "Bug", "Poison"));
        dict.Add("050", new PokeInfo("050", "Diglett", "Ground", "None"));
        dict.Add("050alola", new PokeInfo("050alola", "Diglett", "Ground", "Steel"));
        dict.Add("051", new PokeInfo("051", "Dugtrio", "Ground", "None"));
        dict.Add("051alola", new PokeInfo("051alola", "Dugtrio", "Ground", "Steel"));
        dict.Add("052", new PokeInfo("052", "Meowth", "Normal", "None"));
        dict.Add("052alola", new PokeInfo("052alola", "Meowth", "Dark", "None"));
        dict.Add("052alola1", new PokeInfo("052alola", "Meowth", "Steel", "None"));
        dict.Add("053", new PokeInfo("053", "Persian", "Normal", "None"));
        dict.Add("053alola", new PokeInfo("053alola", "Persian", "Dark", "None"));
        dict.Add("054", new PokeInfo("054", "Psyduck", "Water", "None"));
        dict.Add("055", new PokeInfo("055", "Golduck", "Water", "None"));
        dict.Add("056", new PokeInfo("056", "Mankey", "Fighting", "None"));
        dict.Add("057", new PokeInfo("057", "Primeape", "Fighting", "None"));
        dict.Add("058", new PokeInfo("058", "Growlithe", "Fire", "None"));
        dict.Add("059", new PokeInfo("059", "Arcanine", "Fire", "None"));
        dict.Add("060", new PokeInfo("060", "Poliwag", "Water", "None"));
        dict.Add("061", new PokeInfo("061", "Poliwhirl", "Water", "None"));
        dict.Add("062", new PokeInfo("062", "Poliwrath", "Water", "Fighting"));
        dict.Add("063", new PokeInfo("063", "Abra", "Psychic", "None"));
        dict.Add("064", new PokeInfo("064", "Kadabra", "Psychic", "None"));
        dict.Add("065", new PokeInfo("065", "Alakazam", "Psychic", "None"));
        dict.Add("066", new PokeInfo("066", "Machop", "Fighting", "None"));
        dict.Add("067", new PokeInfo("067", "Machoke", "Fighting", "None"));
        dict.Add("068", new PokeInfo("068", "Machamp", "Fighting", "None"));
        dict.Add("069", new PokeInfo("069", "Bellsprout", "Grass", "Poison"));
        dict.Add("070", new PokeInfo("070", "Weepinbell", "Grass", "Poison"));
        dict.Add("071", new PokeInfo("071", "Victreebel", "Grass", "Poison"));
        dict.Add("072", new PokeInfo("072", "Tentacool", "Water", "Poison"));
        dict.Add("073", new PokeInfo("073", "Tentacruel", "Water", "Poison"));
        dict.Add("074", new PokeInfo("074", "Geodude", "Rock", "Ground"));
        dict.Add("074alola", new PokeInfo("074alola", "Geodude", "Rock", "Electric"));
        dict.Add("075", new PokeInfo("075", "Graveler", "Rock", "Ground"));
        dict.Add("075alola", new PokeInfo("075alola", "Graveler", "Rock", "Electric"));
        dict.Add("076", new PokeInfo("076", "Golem", "Rock", "Ground"));
        dict.Add("076alola", new PokeInfo("076alola", "Golem", "Rock", "Electric"));
        dict.Add("077", new PokeInfo("077", "Ponyta", "Fire", "None"));
        dict.Add("077alola", new PokeInfo("077alola", "Ponyta", "Psychic", "None"));
        dict.Add("078", new PokeInfo("078", "Rapidash", "Fire", "None"));
        dict.Add("078alola", new PokeInfo("078alola", "Rapidash", "Psychic", "Fairy"));
        dict.Add("079", new PokeInfo("079", "Slowpoke", "Water", "Psychic"));
        dict.Add("079alola", new PokeInfo("079alola", "Slowpoke", "Psychic", "None"));
        dict.Add("080", new PokeInfo("080", "Slowbro", "Water", "Psychic"));
        dict.Add("???", new PokeInfo("???", "Slowbro", "???", "None"));
        dict.Add("081", new PokeInfo("081", "Magnemite", "Electric", "Steel"));
        dict.Add("082", new PokeInfo("082", "Magneton", "Electric", "Steel"));
        dict.Add("083", new PokeInfo("083", "Farfetch'd", "Normal", "Flying"));
        dict.Add("083alola", new PokeInfo("083alola", "Farfetch'd", "Fighting", "None"));
        dict.Add("084", new PokeInfo("084", "Doduo", "Normal", "Flying"));
        dict.Add("085", new PokeInfo("085", "Dodrio", "Normal", "Flying"));
        dict.Add("086", new PokeInfo("086", "Seel", "Water", "None"));
        dict.Add("087", new PokeInfo("087", "Dewgong", "Water", "Ice"));
        dict.Add("088", new PokeInfo("088", "Grimer", "Poison", "None"));
        dict.Add("088alola", new PokeInfo("088alola", "Grimer", "Poison", "Dark"));
        dict.Add("089", new PokeInfo("089", "Muk", "Poison", "None"));
        dict.Add("089alola", new PokeInfo("089alola", "Muk", "Poison", "Dark"));
        dict.Add("090", new PokeInfo("090", "Shellder", "Water", "None"));
        dict.Add("091", new PokeInfo("091", "Cloyster", "Water", "Ice"));
        dict.Add("092", new PokeInfo("092", "Gastly", "Ghost", "Poison"));
        dict.Add("093", new PokeInfo("093", "Haunter", "Ghost", "Poison"));
        dict.Add("094", new PokeInfo("094", "Gengar", "Ghost", "Poison"));
        dict.Add("095", new PokeInfo("095", "Onix", "Rock", "Ground"));
        dict.Add("096", new PokeInfo("096", "Drowzee", "Psychic", "None"));
        dict.Add("097", new PokeInfo("097", "Hypno", "Psychic", "None"));
        dict.Add("098", new PokeInfo("098", "Krabby", "Water", "None"));
        dict.Add("099", new PokeInfo("099", "Kingler", "Water", "None"));
        dict.Add("100", new PokeInfo("100", "Voltorb", "Electric", "None"));
        dict.Add("101", new PokeInfo("101", "Electrode", "Electric", "None"));
        dict.Add("102", new PokeInfo("102", "Exeggcute", "Grass", "Psychic"));
        dict.Add("103", new PokeInfo("103", "Exeggutor", "Grass", "Psychic"));
        dict.Add("103alola", new PokeInfo("103alola", "Exeggutor", "Grass", "Dragon"));
        dict.Add("104", new PokeInfo("104", "Cubone", "Ground", "None"));
        dict.Add("105", new PokeInfo("105", "Marowak", "Ground", "None"));
        dict.Add("105alola", new PokeInfo("105alola", "Marowak", "Fire", "Ghost"));
        dict.Add("106", new PokeInfo("106", "Hitmonlee", "Fighting", "None"));
        dict.Add("107", new PokeInfo("107", "Hitmonchan", "Fighting", "None"));
        dict.Add("108", new PokeInfo("108", "Lickitung", "Normal", "None"));
        dict.Add("109", new PokeInfo("109", "Koffing", "Poison", "None"));
        dict.Add("110", new PokeInfo("110", "Weezing", "Poison", "None"));
        dict.Add("110alola", new PokeInfo("110alola", "Weezing", "Poison", "Fairy"));
        dict.Add("111", new PokeInfo("111", "Rhyhorn", "Ground", "Rock"));
        dict.Add("112", new PokeInfo("112", "Rhydon", "Ground", "Rock"));
        dict.Add("113", new PokeInfo("113", "Chansey", "Normal", "None"));
        dict.Add("114", new PokeInfo("114", "Tangela", "Grass", "None"));
        dict.Add("115", new PokeInfo("115", "Kangaskhan", "Normal", "None"));
        dict.Add("116", new PokeInfo("116", "Horsea", "Water", "None"));
        dict.Add("117", new PokeInfo("117", "Seadra", "Water", "None"));
        dict.Add("118", new PokeInfo("118", "Goldeen", "Water", "None"));
        dict.Add("119", new PokeInfo("119", "Seaking", "Water", "None"));
        dict.Add("120", new PokeInfo("120", "Staryu", "Water", "None"));
        dict.Add("121", new PokeInfo("121", "Starmie", "Water", "Psychic"));
        dict.Add("122", new PokeInfo("122", "Mr. Mime", "Psychic", "Fairy"));
        dict.Add("122alola", new PokeInfo("122alola", "Mr. Mime", "Ice", "Psychic"));
        dict.Add("123", new PokeInfo("123", "Scyther", "Bug", "Flying"));
        dict.Add("124", new PokeInfo("124", "Jynx", "Ice", "Psychic"));
        dict.Add("125", new PokeInfo("125", "Electabuzz", "Electric", "None"));
        dict.Add("126", new PokeInfo("126", "Magmar", "Fire", "None"));
        dict.Add("127", new PokeInfo("127", "Pinsir", "Bug", "None"));
        dict.Add("128", new PokeInfo("128", "Tauros", "Normal", "None"));
        dict.Add("129", new PokeInfo("129", "Magikarp", "Water", "None"));
        dict.Add("130", new PokeInfo("130", "Gyarados", "Water", "Flying"));
        dict.Add("131", new PokeInfo("131", "Lapras", "Water", "Ice"));
        dict.Add("132", new PokeInfo("132", "Ditto", "Normal", "None"));
        dict.Add("133", new PokeInfo("133", "Eevee", "Normal", "None"));
        dict.Add("134", new PokeInfo("134", "Vaporeon", "Water", "None"));
        dict.Add("135", new PokeInfo("135", "Jolteon", "Electric", "None"));
        dict.Add("136", new PokeInfo("136", "Flareon", "Fire", "None"));
        dict.Add("137", new PokeInfo("137", "Porygon", "Normal", "None"));
        dict.Add("138", new PokeInfo("138", "Omanyte", "Rock", "Water"));
        dict.Add("139", new PokeInfo("139", "Omastar", "Rock", "Water"));
        dict.Add("140", new PokeInfo("140", "Kabuto", "Rock", "Water"));
        dict.Add("141", new PokeInfo("141", "Kabutops", "Rock", "Water"));
        dict.Add("142", new PokeInfo("142", "Aerodactyl", "Rock", "Flying"));
        dict.Add("143", new PokeInfo("143", "Snorlax", "Normal", "None"));
        dict.Add("144", new PokeInfo("144", "Articuno", "Ice", "Flying"));
        dict.Add("145", new PokeInfo("145", "Zapdos", "Electric", "Flying"));
        dict.Add("146", new PokeInfo("146", "Moltres", "Fire", "Flying"));
        dict.Add("147", new PokeInfo("147", "Dratini", "Dragon", "None"));
        dict.Add("148", new PokeInfo("148", "Dragonair", "Dragon", "None"));
        dict.Add("149", new PokeInfo("149", "Dragonite", "Dragon", "Flying"));
        dict.Add("150", new PokeInfo("150", "Mewtwo", "Psychic", "None"));
        dict.Add("151", new PokeInfo("151", "Mew", "Psychic", "None"));
        dict.Add("152", new PokeInfo("152", "Chikorita", "Grass", "None"));
        dict.Add("153", new PokeInfo("153", "Bayleef", "Grass", "None"));
        dict.Add("154", new PokeInfo("154", "Meganium", "Grass", "None"));
        dict.Add("155", new PokeInfo("155", "Cyndaquil", "Fire", "None"));
        dict.Add("156", new PokeInfo("156", "Quilava", "Fire", "None"));
        dict.Add("157", new PokeInfo("157", "Typhlosion", "Fire", "None"));
        dict.Add("158", new PokeInfo("158", "Totodile", "Water", "None"));
        dict.Add("159", new PokeInfo("159", "Croconaw", "Water", "None"));
        dict.Add("160", new PokeInfo("160", "Feraligatr", "Water", "None"));
        dict.Add("161", new PokeInfo("161", "Sentret", "Normal", "None"));
        dict.Add("162", new PokeInfo("162", "Furret", "Normal", "None"));
        dict.Add("163", new PokeInfo("163", "Hoothoot", "Normal", "Flying"));
        dict.Add("164", new PokeInfo("164", "Noctowl", "Normal", "Flying"));
        dict.Add("165", new PokeInfo("165", "Ledyba", "Bug", "Flying"));
        dict.Add("166", new PokeInfo("166", "Ledian", "Bug", "Flying"));
        dict.Add("167", new PokeInfo("167", "Spinarak", "Bug", "Poison"));
        dict.Add("168", new PokeInfo("168", "Ariados", "Bug", "Poison"));
        dict.Add("169", new PokeInfo("169", "Crobat", "Poison", "Flying"));
        dict.Add("170", new PokeInfo("170", "Chinchou", "Water", "Electric"));
        dict.Add("171", new PokeInfo("171", "Lanturn", "Water", "Electric"));
        dict.Add("172", new PokeInfo("172", "Pichu", "Electric", "None"));
        dict.Add("173", new PokeInfo("173", "Cleffa", "Fairy", "None"));
        dict.Add("174", new PokeInfo("174", "Igglybuff", "Normal", "Fairy"));
        dict.Add("175", new PokeInfo("175", "Togepi", "Fairy", "None"));
        dict.Add("176", new PokeInfo("176", "Togetic", "Fairy", "Flying"));
        dict.Add("177", new PokeInfo("177", "Natu", "Psychic", "Flying"));
        dict.Add("178", new PokeInfo("178", "Xatu", "Psychic", "Flying"));
        dict.Add("179", new PokeInfo("179", "Mareep", "Electric", "None"));
        dict.Add("180", new PokeInfo("180", "Flaaffy", "Electric", "None"));
        dict.Add("181", new PokeInfo("181", "Ampharos", "Electric", "None"));
        dict.Add("182", new PokeInfo("182", "Bellossom", "Grass", "None"));
        dict.Add("183", new PokeInfo("183", "Marill", "Water", "Fairy"));
        dict.Add("184", new PokeInfo("184", "Azumarill", "Water", "Fairy"));
        dict.Add("185", new PokeInfo("185", "Sudowoodo", "Rock", "None"));
        dict.Add("186", new PokeInfo("186", "Politoed", "Water", "None"));
        dict.Add("187", new PokeInfo("187", "Hoppip", "Grass", "Flying"));
        dict.Add("188", new PokeInfo("188", "Skiploom", "Grass", "Flying"));
        dict.Add("189", new PokeInfo("189", "Jumpluff", "Grass", "Flying"));
        dict.Add("190", new PokeInfo("190", "Aipom", "Normal", "None"));
        dict.Add("191", new PokeInfo("191", "Sunkern", "Grass", "None"));
        dict.Add("192", new PokeInfo("192", "Sunflora", "Grass", "None"));
        dict.Add("193", new PokeInfo("193", "Yanma", "Bug", "Flying"));
        dict.Add("194", new PokeInfo("194", "Wooper", "Water", "Ground"));
        dict.Add("195", new PokeInfo("195", "Quagsire", "Water", "Ground"));
        dict.Add("196", new PokeInfo("196", "Espeon", "Psychic", "None"));
        dict.Add("197", new PokeInfo("197", "Umbreon", "Dark", "None"));
        dict.Add("198", new PokeInfo("198", "Murkrow", "Dark", "Flying"));
        dict.Add("199", new PokeInfo("199", "Slowking", "Water", "Psychic"));
        //dict.Add("???", new PokeInfo("???", "Slowking", "???", "None"));
        dict.Add("200", new PokeInfo("200", "Misdreavus", "Ghost", "None"));
        dict.Add("201", new PokeInfo("201", "Unown", "Psychic", "None"));
        dict.Add("202", new PokeInfo("202", "Wobbuffet", "Psychic", "None"));
        dict.Add("203", new PokeInfo("203", "Girafarig", "Normal", "Psychic"));
        dict.Add("204", new PokeInfo("204", "Pineco", "Bug", "None"));
        dict.Add("205", new PokeInfo("205", "Forretress", "Bug", "Steel"));
        dict.Add("206", new PokeInfo("206", "Dunsparce", "Normal", "None"));
        dict.Add("207", new PokeInfo("207", "Gligar", "Ground", "Flying"));
        dict.Add("208", new PokeInfo("208", "Steelix", "Steel", "Ground"));
        dict.Add("209", new PokeInfo("209", "Snubbull", "Fairy", "None"));
        dict.Add("210", new PokeInfo("210", "Granbull", "Fairy", "None"));
        dict.Add("211", new PokeInfo("211", "Qwilfish", "Water", "Poison"));
        dict.Add("212", new PokeInfo("212", "Scizor", "Bug", "Steel"));
        dict.Add("213", new PokeInfo("213", "Shuckle", "Bug", "Rock"));
        dict.Add("214", new PokeInfo("214", "Heracross", "Bug", "Fighting"));
        dict.Add("215", new PokeInfo("215", "Sneasel", "Dark", "Ice"));
        dict.Add("216", new PokeInfo("216", "Teddiursa", "Normal", "None"));
        dict.Add("217", new PokeInfo("217", "Ursaring", "Normal", "None"));
        dict.Add("218", new PokeInfo("218", "Slugma", "Fire", "None"));
        dict.Add("219", new PokeInfo("219", "Magcargo", "Fire", "Rock"));
        dict.Add("220", new PokeInfo("220", "Swinub", "Ice", "Ground"));
        dict.Add("221", new PokeInfo("221", "Piloswine", "Ice", "Ground"));
        dict.Add("222", new PokeInfo("222", "Corsola", "Water", "Rock"));
        dict.Add("222alola", new PokeInfo("222alola", "Corsola", "Ghost", "None"));
        dict.Add("223", new PokeInfo("223", "Remoraid", "Water", "None"));
        dict.Add("224", new PokeInfo("224", "Octillery", "Water", "None"));
        dict.Add("225", new PokeInfo("225", "Delibird", "Ice", "Flying"));
        dict.Add("226", new PokeInfo("226", "Mantine", "Water", "Flying"));
        dict.Add("227", new PokeInfo("227", "Skarmory", "Steel", "Flying"));
        dict.Add("228", new PokeInfo("228", "Houndour", "Dark", "Fire"));
        dict.Add("229", new PokeInfo("229", "Houndoom", "Dark", "Fire"));
        dict.Add("230", new PokeInfo("230", "Kingdra", "Water", "Dragon"));
        dict.Add("231", new PokeInfo("231", "Phanpy", "Ground", "None"));
        dict.Add("232", new PokeInfo("232", "Donphan", "Ground", "None"));
        dict.Add("233", new PokeInfo("233", "Porygon2", "Normal", "None"));
        dict.Add("234", new PokeInfo("234", "Stantler", "Normal", "None"));
        dict.Add("235", new PokeInfo("235", "Smeargle", "Normal", "None"));
        dict.Add("236", new PokeInfo("236", "Tyrogue", "Fighting", "None"));
        dict.Add("237", new PokeInfo("237", "Hitmontop", "Fighting", "None"));
        dict.Add("238", new PokeInfo("238", "Smoochum", "Ice", "Psychic"));
        dict.Add("239", new PokeInfo("239", "Elekid", "Electric", "None"));
        dict.Add("240", new PokeInfo("240", "Magby", "Fire", "None"));
        dict.Add("241", new PokeInfo("241", "Miltank", "Normal", "None"));
        dict.Add("242", new PokeInfo("242", "Blissey", "Normal", "None"));
        dict.Add("243", new PokeInfo("243", "Raikou", "Electric", "None"));
        dict.Add("244", new PokeInfo("244", "Entei", "Fire", "None"));
        dict.Add("245", new PokeInfo("245", "Suicune", "Water", "None"));
        dict.Add("246", new PokeInfo("246", "Larvitar", "Rock", "Ground"));
        dict.Add("247", new PokeInfo("247", "Pupitar", "Rock", "Ground"));
        dict.Add("248", new PokeInfo("248", "Tyranitar", "Rock", "Dark"));
        dict.Add("249", new PokeInfo("249", "Lugia", "Psychic", "Flying"));
        dict.Add("250", new PokeInfo("250", "Ho-Oh", "Fire", "Flying"));
        dict.Add("251", new PokeInfo("251", "Celebi", "Psychic", "Grass"));
        dict.Add("252", new PokeInfo("252", "Treecko", "Grass", "None"));
        dict.Add("253", new PokeInfo("253", "Grovyle", "Grass", "None"));
        dict.Add("254", new PokeInfo("254", "Sceptile", "Grass", "None"));
        dict.Add("255", new PokeInfo("255", "Torchic", "Fire", "None"));
        dict.Add("256", new PokeInfo("256", "Combusken", "Fire", "Fighting"));
        dict.Add("257", new PokeInfo("257", "Blaziken", "Fire", "Fighting"));
        dict.Add("258", new PokeInfo("258", "Mudkip", "Water", "None"));
        dict.Add("259", new PokeInfo("259", "Marshtomp", "Water", "Ground"));
        dict.Add("260", new PokeInfo("260", "Swampert", "Water", "Ground"));
        dict.Add("261", new PokeInfo("261", "Poochyena", "Dark", "None"));
        dict.Add("262", new PokeInfo("262", "Mightyena", "Dark", "None"));
        dict.Add("263", new PokeInfo("263", "Zigzagoon", "Normal", "None"));
        dict.Add("263alola", new PokeInfo("263alola", "Zigzagoon", "Dark", "Normal"));
        dict.Add("264", new PokeInfo("264", "Linoone", "Normal", "None"));
        dict.Add("264alola", new PokeInfo("264alola", "Linoone", "Dark", "Normal"));
        dict.Add("265", new PokeInfo("265", "Wurmple", "Bug", "None"));
        dict.Add("266", new PokeInfo("266", "Silcoon", "Bug", "None"));
        dict.Add("267", new PokeInfo("267", "Beautifly", "Bug", "Flying"));
        dict.Add("268", new PokeInfo("268", "Cascoon", "Bug", "None"));
        dict.Add("269", new PokeInfo("269", "Dustox", "Bug", "Poison"));
        dict.Add("270", new PokeInfo("270", "Lotad", "Water", "Grass"));
        dict.Add("271", new PokeInfo("271", "Lombre", "Water", "Grass"));
        dict.Add("272", new PokeInfo("272", "Ludicolo", "Water", "Grass"));
        dict.Add("273", new PokeInfo("273", "Seedot", "Grass", "None"));
        dict.Add("274", new PokeInfo("274", "Nuzleaf", "Grass", "Dark"));
        dict.Add("275", new PokeInfo("275", "Shiftry", "Grass", "Dark"));
        dict.Add("276", new PokeInfo("276", "Taillow", "Normal", "Flying"));
        dict.Add("277", new PokeInfo("277", "Swellow", "Normal", "Flying"));
        dict.Add("278", new PokeInfo("278", "Wingull", "Water", "Flying"));
        dict.Add("279", new PokeInfo("279", "Pelipper", "Water", "Flying"));
        dict.Add("280", new PokeInfo("280", "Ralts", "Psychic", "Fairy"));
        dict.Add("281", new PokeInfo("281", "Kirlia", "Psychic", "Fairy"));
        dict.Add("282", new PokeInfo("282", "Gardevoir", "Psychic", "Fairy"));
        dict.Add("283", new PokeInfo("283", "Surskit", "Bug", "Water"));
        dict.Add("284", new PokeInfo("284", "Masquerain", "Bug", "Flying"));
        dict.Add("285", new PokeInfo("285", "Shroomish", "Grass", "None"));
        dict.Add("286", new PokeInfo("286", "Breloom", "Grass", "Fighting"));
        dict.Add("287", new PokeInfo("287", "Slakoth", "Normal", "None"));
        dict.Add("288", new PokeInfo("288", "Vigoroth", "Normal", "None"));
        dict.Add("289", new PokeInfo("289", "Slaking", "Normal", "None"));
        dict.Add("290", new PokeInfo("290", "Nincada", "Bug", "Ground"));
        dict.Add("291", new PokeInfo("291", "Ninjask", "Bug", "Flying"));
        dict.Add("292", new PokeInfo("292", "Shedinja", "Bug", "Ghost"));
        dict.Add("293", new PokeInfo("293", "Whismur", "Normal", "None"));
        dict.Add("294", new PokeInfo("294", "Loudred", "Normal", "None"));
        dict.Add("295", new PokeInfo("295", "Exploud", "Normal", "None"));
        dict.Add("296", new PokeInfo("296", "Makuhita", "Fighting", "None"));
        dict.Add("297", new PokeInfo("297", "Hariyama", "Fighting", "None"));
        dict.Add("298", new PokeInfo("298", "Azurill", "Normal", "Fairy"));
        dict.Add("299", new PokeInfo("299", "Nosepass", "Rock", "None"));
        dict.Add("300", new PokeInfo("300", "Skitty", "Normal", "None"));
        dict.Add("301", new PokeInfo("301", "Delcatty", "Normal", "None"));
        dict.Add("302", new PokeInfo("302", "Sableye", "Dark", "Ghost"));
        dict.Add("303", new PokeInfo("303", "Mawile", "Steel", "Fairy"));
        dict.Add("304", new PokeInfo("304", "Aron", "Steel", "Rock"));
        dict.Add("305", new PokeInfo("305", "Lairon", "Steel", "Rock"));
        dict.Add("306", new PokeInfo("306", "Aggron", "Steel", "Rock"));
        dict.Add("307", new PokeInfo("307", "Meditite", "Fighting", "Psychic"));
        dict.Add("308", new PokeInfo("308", "Medicham", "Fighting", "Psychic"));
        dict.Add("309", new PokeInfo("309", "Electrike", "Electric", "None"));
        dict.Add("310", new PokeInfo("310", "Manectric", "Electric", "None"));
        dict.Add("311", new PokeInfo("311", "Plusle", "Electric", "None"));
        dict.Add("312", new PokeInfo("312", "Minun", "Electric", "None"));
        dict.Add("313", new PokeInfo("313", "Volbeat", "Bug", "None"));
        dict.Add("314", new PokeInfo("314", "Illumise", "Bug", "None"));
        dict.Add("315", new PokeInfo("315", "Roselia", "Grass", "Poison"));
        dict.Add("316", new PokeInfo("316", "Gulpin", "Poison", "None"));
        dict.Add("317", new PokeInfo("317", "Swalot", "Poison", "None"));
        dict.Add("318", new PokeInfo("318", "Carvanha", "Water", "Dark"));
        dict.Add("319", new PokeInfo("319", "Sharpedo", "Water", "Dark"));
        dict.Add("320", new PokeInfo("320", "Wailmer", "Water", "None"));
        dict.Add("321", new PokeInfo("321", "Wailord", "Water", "None"));
        dict.Add("322", new PokeInfo("322", "Numel", "Fire", "Ground"));
        dict.Add("323", new PokeInfo("323", "Camerupt", "Fire", "Ground"));
        dict.Add("324", new PokeInfo("324", "Torkoal", "Fire", "None"));
        dict.Add("325", new PokeInfo("325", "Spoink", "Psychic", "None"));
        dict.Add("326", new PokeInfo("326", "Grumpig", "Psychic", "None"));
        dict.Add("327", new PokeInfo("327", "Spinda", "Normal", "None"));
        dict.Add("328", new PokeInfo("328", "Trapinch", "Ground", "None"));
        dict.Add("329", new PokeInfo("329", "Vibrava", "Ground", "Dragon"));
        dict.Add("330", new PokeInfo("330", "Flygon", "Ground", "Dragon"));
        dict.Add("331", new PokeInfo("331", "Cacnea", "Grass", "None"));
        dict.Add("332", new PokeInfo("332", "Cacturne", "Grass", "Dark"));
        dict.Add("333", new PokeInfo("333", "Swablu", "Normal", "Flying"));
        dict.Add("334", new PokeInfo("334", "Altaria", "Dragon", "Flying"));
        dict.Add("335", new PokeInfo("335", "Zangoose", "Normal", "None"));
        dict.Add("336", new PokeInfo("336", "Seviper", "Poison", "None"));
        dict.Add("337", new PokeInfo("337", "Lunatone", "Rock", "Psychic"));
        dict.Add("338", new PokeInfo("338", "Solrock", "Rock", "Psychic"));
        dict.Add("339", new PokeInfo("339", "Barboach", "Water", "Ground"));
        dict.Add("340", new PokeInfo("340", "Whiscash", "Water", "Ground"));
        dict.Add("341", new PokeInfo("341", "Corphish", "Water", "None"));
        dict.Add("342", new PokeInfo("342", "Crawdaunt", "Water", "Dark"));
        dict.Add("343", new PokeInfo("343", "Baltoy", "Ground", "Psychic"));
        dict.Add("344", new PokeInfo("344", "Claydol", "Ground", "Psychic"));
        dict.Add("345", new PokeInfo("345", "Lileep", "Rock", "Grass"));
        dict.Add("346", new PokeInfo("346", "Cradily", "Rock", "Grass"));
        dict.Add("347", new PokeInfo("347", "Anorith", "Rock", "Bug"));
        dict.Add("348", new PokeInfo("348", "Armaldo", "Rock", "Bug"));
        dict.Add("349", new PokeInfo("349", "Feebas", "Water", "None"));
        dict.Add("350", new PokeInfo("350", "Milotic", "Water", "None"));
        dict.Add("351", new PokeInfo("351", "Castform", "Normal", "None"));
        dict.Add("351alola", new PokeInfo("351alola", "Castform", "Fire", "None"));
        dict.Add("351alola1", new PokeInfo("351alola", "Castform", "Water", "None"));
        dict.Add("351alola2", new PokeInfo("351alola", "Castform", "Ice", "None"));
        dict.Add("352", new PokeInfo("352", "Kecleon", "Normal", "None"));
        dict.Add("353", new PokeInfo("353", "Shuppet", "Ghost", "None"));
        dict.Add("354", new PokeInfo("354", "Banette", "Ghost", "None"));
        dict.Add("355", new PokeInfo("355", "Duskull", "Ghost", "None"));
        dict.Add("356", new PokeInfo("356", "Dusclops", "Ghost", "None"));
        dict.Add("357", new PokeInfo("357", "Tropius", "Grass", "Flying"));
        dict.Add("358", new PokeInfo("358", "Chimecho", "Psychic", "None"));
        dict.Add("359", new PokeInfo("359", "Absol", "Dark", "None"));
        dict.Add("360", new PokeInfo("360", "Wynaut", "Psychic", "None"));
        dict.Add("361", new PokeInfo("361", "Snorunt", "Ice", "None"));
        dict.Add("362", new PokeInfo("362", "Glalie", "Ice", "None"));
        dict.Add("363", new PokeInfo("363", "Spheal", "Ice", "Water"));
        dict.Add("364", new PokeInfo("364", "Sealeo", "Ice", "Water"));
        dict.Add("365", new PokeInfo("365", "Walrein", "Ice", "Water"));
        dict.Add("366", new PokeInfo("366", "Clamperl", "Water", "None"));
        dict.Add("367", new PokeInfo("367", "Huntail", "Water", "None"));
        dict.Add("368", new PokeInfo("368", "Gorebyss", "Water", "None"));
        dict.Add("369", new PokeInfo("369", "Relicanth", "Water", "Rock"));
        dict.Add("370", new PokeInfo("370", "Luvdisc", "Water", "None"));
        dict.Add("371", new PokeInfo("371", "Bagon", "Dragon", "None"));
        dict.Add("372", new PokeInfo("372", "Shelgon", "Dragon", "None"));
        dict.Add("373", new PokeInfo("373", "Salamence", "Dragon", "Flying"));
        dict.Add("374", new PokeInfo("374", "Beldum", "Steel", "Psychic"));
        dict.Add("375", new PokeInfo("375", "Metang", "Steel", "Psychic"));
        dict.Add("376", new PokeInfo("376", "Metagross", "Steel", "Psychic"));
        dict.Add("377", new PokeInfo("377", "Regirock", "Rock", "None"));
        dict.Add("378", new PokeInfo("378", "Regice", "Ice", "None"));
        dict.Add("379", new PokeInfo("379", "Registeel", "Steel", "None"));
        dict.Add("380", new PokeInfo("380", "Latias", "Dragon", "Psychic"));
        dict.Add("381", new PokeInfo("381", "Latios", "Dragon", "Psychic"));
        dict.Add("382", new PokeInfo("382", "Kyogre", "Water", "None"));
        dict.Add("383", new PokeInfo("383", "Groudon", "Ground", "None"));
        dict.Add("384", new PokeInfo("384", "Rayquaza", "Dragon", "Flying"));
        dict.Add("385", new PokeInfo("385", "Jirachi", "Steel", "Psychic"));
        dict.Add("386", new PokeInfo("386", "Deoxys", "Psychic", "None"));
        dict.Add("386alola", new PokeInfo("386alola", "Deoxys", "Psychic", "None"));
        dict.Add("386alola1", new PokeInfo("386alola", "Deoxys", "Psychic", "None"));
        dict.Add("386alola2", new PokeInfo("386alola", "Deoxys", "Psychic", "None"));
        dict.Add("387", new PokeInfo("387", "Turtwig", "Grass", "None"));
        dict.Add("388", new PokeInfo("388", "Grotle", "Grass", "None"));
        dict.Add("389", new PokeInfo("389", "Torterra", "Grass", "Ground"));
        dict.Add("390", new PokeInfo("390", "Chimchar", "Fire", "None"));
        dict.Add("391", new PokeInfo("391", "Monferno", "Fire", "Fighting"));
        dict.Add("392", new PokeInfo("392", "Infernape", "Fire", "Fighting"));
        dict.Add("393", new PokeInfo("393", "Piplup", "Water", "None"));
        dict.Add("394", new PokeInfo("394", "Prinplup", "Water", "None"));
        dict.Add("395", new PokeInfo("395", "Empoleon", "Water", "Steel"));
        dict.Add("396", new PokeInfo("396", "Starly", "Normal", "Flying"));
        dict.Add("397", new PokeInfo("397", "Staravia", "Normal", "Flying"));
        dict.Add("398", new PokeInfo("398", "Staraptor", "Normal", "Flying"));
        dict.Add("399", new PokeInfo("399", "Bidoof", "Normal", "None"));
        dict.Add("400", new PokeInfo("400", "Bibarel", "Normal", "Water"));
        dict.Add("401", new PokeInfo("401", "Kricketot", "Bug", "None"));
        dict.Add("402", new PokeInfo("402", "Kricketune", "Bug", "None"));
        dict.Add("403", new PokeInfo("403", "Shinx", "Electric", "None"));
        dict.Add("404", new PokeInfo("404", "Luxio", "Electric", "None"));
        dict.Add("405", new PokeInfo("405", "Luxray", "Electric", "None"));
        dict.Add("406", new PokeInfo("406", "Budew", "Grass", "Poison"));
        dict.Add("407", new PokeInfo("407", "Roserade", "Grass", "Poison"));
        dict.Add("408", new PokeInfo("408", "Cranidos", "Rock", "None"));
        dict.Add("409", new PokeInfo("409", "Rampardos", "Rock", "None"));
        dict.Add("410", new PokeInfo("410", "Shieldon", "Rock", "Steel"));
        dict.Add("411", new PokeInfo("411", "Bastiodon", "Rock", "Steel"));
        dict.Add("412", new PokeInfo("412", "Burmy", "Bug", "None"));
        dict.Add("412alola", new PokeInfo("412alola", "Burmy", "Bug", "None"));
        dict.Add("412alola1", new PokeInfo("412alola", "Burmy", "Bug", "None"));
        dict.Add("413", new PokeInfo("413", "Wormadam", "Bug", "Grass"));
        dict.Add("413alola1", new PokeInfo("413alola", "Wormadam", "Bug", "Ground"));
        dict.Add("413alola2", new PokeInfo("413alola", "Wormadam", "Bug", "Steel"));
        dict.Add("414", new PokeInfo("414", "Mothim", "Bug", "Flying"));
        dict.Add("415", new PokeInfo("415", "Combee", "Bug", "Flying"));
        dict.Add("416", new PokeInfo("416", "Vespiquen", "Bug", "Flying"));
        dict.Add("417", new PokeInfo("417", "Pachirisu", "Electric", "None"));
        dict.Add("418", new PokeInfo("418", "Buizel", "Water", "None"));
        dict.Add("419", new PokeInfo("419", "Floatzel", "Water", "None"));
        dict.Add("420", new PokeInfo("420", "Cherubi", "Grass", "None"));
        dict.Add("421", new PokeInfo("421", "Cherrim", "Grass", "None"));
        dict.Add("422", new PokeInfo("422", "Shellos", "Water", "None"));
        dict.Add("422alola", new PokeInfo("422alola", "Shellos", "Water", "None"));
        dict.Add("423", new PokeInfo("423", "Gastrodon", "Water", "Ground"));
        dict.Add("423alola", new PokeInfo("423alola", "Gastrodon", "Water", "Ground"));
        dict.Add("424", new PokeInfo("424", "Ambipom", "Normal", "None"));
        dict.Add("425", new PokeInfo("425", "Drifloon", "Ghost", "Flying"));
        dict.Add("426", new PokeInfo("426", "Drifblim", "Ghost", "Flying"));
        dict.Add("427", new PokeInfo("427", "Buneary", "Normal", "None"));
        dict.Add("428", new PokeInfo("428", "Lopunny", "Normal", "None"));
        dict.Add("429", new PokeInfo("429", "Mismagius", "Ghost", "None"));
        dict.Add("430", new PokeInfo("430", "Honchkrow", "Dark", "Flying"));
        dict.Add("431", new PokeInfo("431", "Glameow", "Normal", "None"));
        dict.Add("432", new PokeInfo("432", "Purugly", "Normal", "None"));
        dict.Add("433", new PokeInfo("433", "Chingling", "Psychic", "None"));
        dict.Add("434", new PokeInfo("434", "Stunky", "Poison", "Dark"));
        dict.Add("435", new PokeInfo("435", "Skuntank", "Poison", "Dark"));
        dict.Add("436", new PokeInfo("436", "Bronzor", "Steel", "Psychic"));
        dict.Add("437", new PokeInfo("437", "Bronzong", "Steel", "Psychic"));
        dict.Add("438", new PokeInfo("438", "Bonsly", "Rock", "None"));
        dict.Add("439", new PokeInfo("439", "Mime Jr.", "Psychic", "Fairy"));
        dict.Add("440", new PokeInfo("440", "Happiny", "Normal", "None"));
        dict.Add("441", new PokeInfo("441", "Chatot", "Normal", "Flying"));
        dict.Add("442", new PokeInfo("442", "Spiritomb", "Ghost", "Dark"));
        dict.Add("443", new PokeInfo("443", "Gible", "Dragon", "Ground"));
        dict.Add("444", new PokeInfo("444", "Gabite", "Dragon", "Ground"));
        dict.Add("445", new PokeInfo("445", "Garchomp", "Dragon", "Ground"));
        dict.Add("446", new PokeInfo("446", "Munchlax", "Normal", "None"));
        dict.Add("447", new PokeInfo("447", "Riolu", "Fighting", "None"));
        dict.Add("448", new PokeInfo("448", "Lucario", "Fighting", "Steel"));
        dict.Add("449", new PokeInfo("449", "Hippopotas", "Ground", "None"));
        dict.Add("450", new PokeInfo("450", "Hippowdon", "Ground", "None"));
        dict.Add("451", new PokeInfo("451", "Skorupi", "Poison", "Bug"));
        dict.Add("452", new PokeInfo("452", "Drapion", "Poison", "Dark"));
        dict.Add("453", new PokeInfo("453", "Croagunk", "Poison", "Fighting"));
        dict.Add("454", new PokeInfo("454", "Toxicroak", "Poison", "Fighting"));
        dict.Add("455", new PokeInfo("455", "Carnivine", "Grass", "None"));
        dict.Add("456", new PokeInfo("456", "Finneon", "Water", "None"));
        dict.Add("457", new PokeInfo("457", "Lumineon", "Water", "None"));
        dict.Add("458", new PokeInfo("458", "Mantyke", "Water", "Flying"));
        dict.Add("459", new PokeInfo("459", "Snover", "Grass", "Ice"));
        dict.Add("460", new PokeInfo("460", "Abomasnow", "Grass", "Ice"));
        dict.Add("461", new PokeInfo("461", "Weavile", "Dark", "Ice"));
        dict.Add("462", new PokeInfo("462", "Magnezone", "Electric", "Steel"));
        dict.Add("463", new PokeInfo("463", "Lickilicky", "Normal", "None"));
        dict.Add("464", new PokeInfo("464", "Rhyperior", "Ground", "Rock"));
        dict.Add("465", new PokeInfo("465", "Tangrowth", "Grass", "None"));
        dict.Add("466", new PokeInfo("466", "Electivire", "Electric", "None"));
        dict.Add("467", new PokeInfo("467", "Magmortar", "Fire", "None"));
        dict.Add("468", new PokeInfo("468", "Togekiss", "Fairy", "Flying"));
        dict.Add("469", new PokeInfo("469", "Yanmega", "Bug", "Flying"));
        dict.Add("470", new PokeInfo("470", "Leafeon", "Grass", "None"));
        dict.Add("471", new PokeInfo("471", "Glaceon", "Ice", "None"));
        dict.Add("472", new PokeInfo("472", "Gliscor", "Ground", "Flying"));
        dict.Add("473", new PokeInfo("473", "Mamoswine", "Ice", "Ground"));
        dict.Add("474", new PokeInfo("474", "Porygon-Z", "Normal", "None"));
        dict.Add("475", new PokeInfo("475", "Gallade", "Psychic", "Fighting"));
        dict.Add("476", new PokeInfo("476", "Probopass", "Rock", "Steel"));
        dict.Add("477", new PokeInfo("477", "Dusknoir", "Ghost", "None"));
        dict.Add("478", new PokeInfo("478", "Froslass", "Ice", "Ghost"));
        dict.Add("479", new PokeInfo("479", "Rotom", "Electric", "Ghost"));
        dict.Add("479alola", new PokeInfo("479alola", "Rotom", "Electric", "Fire"));
        dict.Add("479alola1", new PokeInfo("479alola", "Rotom", "Electric", "Water"));
        dict.Add("479alola2", new PokeInfo("479alola", "Rotom", "Electric", "Ice"));
        dict.Add("479alola3", new PokeInfo("479alola", "Rotom", "Electric", "Flying"));
        dict.Add("479alola4", new PokeInfo("479alola", "Rotom", "Electric", "Grass"));
        dict.Add("480", new PokeInfo("480", "Uxie", "Psychic", "None"));
        dict.Add("481", new PokeInfo("481", "Mesprit", "Psychic", "None"));
        dict.Add("482", new PokeInfo("482", "Azelf", "Psychic", "None"));
        dict.Add("483", new PokeInfo("483", "Dialga", "Steel", "Dragon"));
        dict.Add("484", new PokeInfo("484", "Palkia", "Water", "Dragon"));
        dict.Add("485", new PokeInfo("485", "Heatran", "Fire", "Steel"));
        dict.Add("486", new PokeInfo("486", "Regigigas", "Normal", "None"));
        dict.Add("487", new PokeInfo("487", "Giratina", "Ghost", "Dragon"));
        dict.Add("487alola", new PokeInfo("487alola", "Giratina", "Ghost", "Dragon"));
        dict.Add("488", new PokeInfo("488", "Cresselia", "Psychic", "None"));
        dict.Add("489", new PokeInfo("489", "Phione", "Water", "None"));
        dict.Add("490", new PokeInfo("490", "Manaphy", "Water", "None"));
        dict.Add("491", new PokeInfo("491", "Darkrai", "Dark", "None"));
        dict.Add("492", new PokeInfo("492", "Shaymin", "Grass", "None"));
        dict.Add("492alola", new PokeInfo("492alola", "Shaymin", "Grass", "Flying"));
        dict.Add("493", new PokeInfo("493", "Arceus", "Normal", "None"));
        dict.Add("494", new PokeInfo("494", "Victini", "Psychic", "Fire"));
        dict.Add("495", new PokeInfo("495", "Snivy", "Grass", "None"));
        dict.Add("496", new PokeInfo("496", "Servine", "Grass", "None"));
        dict.Add("497", new PokeInfo("497", "Serperior", "Grass", "None"));
        dict.Add("498", new PokeInfo("498", "Tepig", "Fire", "None"));
        dict.Add("499", new PokeInfo("499", "Pignite", "Fire", "Fighting"));
        dict.Add("500", new PokeInfo("500", "Emboar", "Fire", "Fighting"));
        dict.Add("501", new PokeInfo("501", "Oshawott", "Water", "None"));
        dict.Add("502", new PokeInfo("502", "Dewott", "Water", "None"));
        dict.Add("503", new PokeInfo("503", "Samurott", "Water", "None"));
        dict.Add("504", new PokeInfo("504", "Patrat", "Normal", "None"));
        dict.Add("505", new PokeInfo("505", "Watchog", "Normal", "None"));
        dict.Add("506", new PokeInfo("506", "Lillipup", "Normal", "None"));
        dict.Add("507", new PokeInfo("507", "Herdier", "Normal", "None"));
        dict.Add("508", new PokeInfo("508", "Stoutland", "Normal", "None"));
        dict.Add("509", new PokeInfo("509", "Purrloin", "Dark", "None"));
        dict.Add("510", new PokeInfo("510", "Liepard", "Dark", "None"));
        dict.Add("511", new PokeInfo("511", "Pansage", "Grass", "None"));
        dict.Add("512", new PokeInfo("512", "Simisage", "Grass", "None"));
        dict.Add("513", new PokeInfo("513", "Pansear", "Fire", "None"));
        dict.Add("514", new PokeInfo("514", "Simisear", "Fire", "None"));
        dict.Add("515", new PokeInfo("515", "Panpour", "Water", "None"));
        dict.Add("516", new PokeInfo("516", "Simipour", "Water", "None"));
        dict.Add("517", new PokeInfo("517", "Munna", "Psychic", "None"));
        dict.Add("518", new PokeInfo("518", "Musharna", "Psychic", "None"));
        dict.Add("519", new PokeInfo("519", "Pidove", "Normal", "Flying"));
        dict.Add("520", new PokeInfo("520", "Tranquill", "Normal", "Flying"));
        dict.Add("521", new PokeInfo("521", "Unfezant", "Normal", "Flying"));
        dict.Add("521alola", new PokeInfo("521alola", "Unfezant", "Normal", "Flying"));
        dict.Add("522", new PokeInfo("522", "Blitzle", "Electric", "None"));
        dict.Add("523", new PokeInfo("523", "Zebstrika", "Electric", "None"));
        dict.Add("524", new PokeInfo("524", "Roggenrola", "Rock", "None"));
        dict.Add("525", new PokeInfo("525", "Boldore", "Rock", "None"));
        dict.Add("526", new PokeInfo("526", "Gigalith", "Rock", "None"));
        dict.Add("527", new PokeInfo("527", "Woobat", "Psychic", "Flying"));
        dict.Add("528", new PokeInfo("528", "Swoobat", "Psychic", "Flying"));
        dict.Add("529", new PokeInfo("529", "Drilbur", "Ground", "None"));
        dict.Add("530", new PokeInfo("530", "Excadrill", "Ground", "Steel"));
        dict.Add("531", new PokeInfo("531", "Audino", "Normal", "None"));
        dict.Add("532", new PokeInfo("532", "Timburr", "Fighting", "None"));
        dict.Add("533", new PokeInfo("533", "Gurdurr", "Fighting", "None"));
        dict.Add("534", new PokeInfo("534", "Conkeldurr", "Fighting", "None"));
        dict.Add("535", new PokeInfo("535", "Tympole", "Water", "None"));
        dict.Add("536", new PokeInfo("536", "Palpitoad", "Water", "Ground"));
        dict.Add("537", new PokeInfo("537", "Seismitoad", "Water", "Ground"));
        dict.Add("538", new PokeInfo("538", "Throh", "Fighting", "None"));
        dict.Add("539", new PokeInfo("539", "Sawk", "Fighting", "None"));
        dict.Add("540", new PokeInfo("540", "Sewaddle", "Bug", "Grass"));
        dict.Add("541", new PokeInfo("541", "Swadloon", "Bug", "Grass"));
        dict.Add("542", new PokeInfo("542", "Leavanny", "Bug", "Grass"));
        dict.Add("543", new PokeInfo("543", "Venipede", "Bug", "Poison"));
        dict.Add("544", new PokeInfo("544", "Whirlipede", "Bug", "Poison"));
        dict.Add("545", new PokeInfo("545", "Scolipede", "Bug", "Poison"));
        dict.Add("546", new PokeInfo("546", "Cottonee", "Grass", "Fairy"));
        dict.Add("547", new PokeInfo("547", "Whimsicott", "Grass", "Fairy"));
        dict.Add("548", new PokeInfo("548", "Petilil", "Grass", "None"));
        dict.Add("549", new PokeInfo("549", "Lilligant", "Grass", "None"));
        dict.Add("550", new PokeInfo("550", "Basculin", "Water", "None"));
        dict.Add("550alola", new PokeInfo("550alola", "Basculin", "Water", "None"));
        dict.Add("551", new PokeInfo("551", "Sandile", "Ground", "Dark"));
        dict.Add("552", new PokeInfo("552", "Krokorok", "Ground", "Dark"));
        dict.Add("553", new PokeInfo("553", "Krookodile", "Ground", "Dark"));
        dict.Add("554", new PokeInfo("554", "Darumaka", "Fire", "None"));
        dict.Add("554alola", new PokeInfo("554alola", "Darumaka", "Ice", "None"));
        dict.Add("555", new PokeInfo("555", "Darmanitan", "Fire", "None"));
        dict.Add("555alola", new PokeInfo("555alola", "Darmanitan", "Fire", "Psychic"));
        dict.Add("555alola1", new PokeInfo("555alola", "Darmanitan", "Ice", "None"));
        dict.Add("555alola2", new PokeInfo("555alola", "Darmanitan", "Ice", "Fire"));
        dict.Add("556", new PokeInfo("556", "Maractus", "Grass", "None"));
        dict.Add("557", new PokeInfo("557", "Dwebble", "Bug", "Rock"));
        dict.Add("558", new PokeInfo("558", "Crustle", "Bug", "Rock"));
        dict.Add("559", new PokeInfo("559", "Scraggy", "Dark", "Fighting"));
        dict.Add("560", new PokeInfo("560", "Scrafty", "Dark", "Fighting"));
        dict.Add("561", new PokeInfo("561", "Sigilyph", "Psychic", "Flying"));
        dict.Add("562", new PokeInfo("562", "Yamask", "Ghost", "None"));
        dict.Add("562alola", new PokeInfo("562alola", "Yamask", "Ground", "Ghost"));
        dict.Add("563", new PokeInfo("563", "Cofagrigus", "Ghost", "None"));
        dict.Add("564", new PokeInfo("564", "Tirtouga", "Water", "Rock"));
        dict.Add("565", new PokeInfo("565", "Carracosta", "Water", "Rock"));
        dict.Add("566", new PokeInfo("566", "Archen", "Rock", "Flying"));
        dict.Add("567", new PokeInfo("567", "Archeops", "Rock", "Flying"));
        dict.Add("568", new PokeInfo("568", "Trubbish", "Poison", "None"));
        dict.Add("569", new PokeInfo("569", "Garbodor", "Poison", "None"));
        dict.Add("570", new PokeInfo("570", "Zorua", "Dark", "None"));
        dict.Add("571", new PokeInfo("571", "Zoroark", "Dark", "None"));
        dict.Add("572", new PokeInfo("572", "Minccino", "Normal", "None"));
        dict.Add("573", new PokeInfo("573", "Cinccino", "Normal", "None"));
        dict.Add("574", new PokeInfo("574", "Gothita", "Psychic", "None"));
        dict.Add("575", new PokeInfo("575", "Gothorita", "Psychic", "None"));
        dict.Add("576", new PokeInfo("576", "Gothitelle", "Psychic", "None"));
        dict.Add("577", new PokeInfo("577", "Solosis", "Psychic", "None"));
        dict.Add("578", new PokeInfo("578", "Duosion", "Psychic", "None"));
        dict.Add("579", new PokeInfo("579", "Reuniclus", "Psychic", "None"));
        dict.Add("580", new PokeInfo("580", "Ducklett", "Water", "Flying"));
        dict.Add("581", new PokeInfo("581", "Swanna", "Water", "Flying"));
        dict.Add("582", new PokeInfo("582", "Vanillite", "Ice", "None"));
        dict.Add("583", new PokeInfo("583", "Vanillish", "Ice", "None"));
        dict.Add("584", new PokeInfo("584", "Vanilluxe", "Ice", "None"));
        dict.Add("585", new PokeInfo("585", "Deerling", "Normal", "Grass"));
        dict.Add("586", new PokeInfo("586", "Sawsbuck", "Normal", "Grass"));
        dict.Add("587", new PokeInfo("587", "Emolga", "Electric", "Flying"));
        dict.Add("588", new PokeInfo("588", "Karrablast", "Bug", "None"));
        dict.Add("589", new PokeInfo("589", "Escavalier", "Bug", "Steel"));
        dict.Add("590", new PokeInfo("590", "Foongus", "Grass", "Poison"));
        dict.Add("591", new PokeInfo("591", "Amoonguss", "Grass", "Poison"));
        dict.Add("592", new PokeInfo("592", "Frillish", "Water", "Ghost"));
        dict.Add("592alola", new PokeInfo("592alola", "Frillish", "Water", "Ghost"));
        dict.Add("593", new PokeInfo("593", "Jellicent", "Water", "Ghost"));
        dict.Add("593alola", new PokeInfo("593alola", "Jellicent", "Water", "Ghost"));
        dict.Add("594", new PokeInfo("594", "Alomomola", "Water", "None"));
        dict.Add("595", new PokeInfo("595", "Joltik", "Bug", "Electric"));
        dict.Add("596", new PokeInfo("596", "Galvantula", "Bug", "Electric"));
        dict.Add("597", new PokeInfo("597", "Ferroseed", "Grass", "Steel"));
        dict.Add("598", new PokeInfo("598", "Ferrothorn", "Grass", "Steel"));
        dict.Add("599", new PokeInfo("599", "Klink", "Steel", "None"));
        dict.Add("600", new PokeInfo("600", "Klang", "Steel", "None"));
        dict.Add("601", new PokeInfo("601", "Klinklang", "Steel", "None"));
        dict.Add("602", new PokeInfo("602", "Tynamo", "Electric", "None"));
        dict.Add("603", new PokeInfo("603", "Eelektrik", "Electric", "None"));
        dict.Add("604", new PokeInfo("604", "Eelektross", "Electric", "None"));
        dict.Add("605", new PokeInfo("605", "Elgyem", "Psychic", "None"));
        dict.Add("606", new PokeInfo("606", "Beheeyem", "Psychic", "None"));
        dict.Add("607", new PokeInfo("607", "Litwick", "Ghost", "Fire"));
        dict.Add("608", new PokeInfo("608", "Lampent", "Ghost", "Fire"));
        dict.Add("609", new PokeInfo("609", "Chandelure", "Ghost", "Fire"));
        dict.Add("610", new PokeInfo("610", "Axew", "Dragon", "None"));
        dict.Add("611", new PokeInfo("611", "Fraxure", "Dragon", "None"));
        dict.Add("612", new PokeInfo("612", "Haxorus", "Dragon", "None"));
        dict.Add("613", new PokeInfo("613", "Cubchoo", "Ice", "None"));
        dict.Add("614", new PokeInfo("614", "Beartic", "Ice", "None"));
        dict.Add("615", new PokeInfo("615", "Cryogonal", "Ice", "None"));
        dict.Add("616", new PokeInfo("616", "Shelmet", "Bug", "None"));
        dict.Add("617", new PokeInfo("617", "Accelgor", "Bug", "None"));
        dict.Add("618", new PokeInfo("618", "Stunfisk", "Ground", "Electric"));
        dict.Add("618alola", new PokeInfo("618alola", "Stunfisk", "Ground", "Steel"));
        dict.Add("619", new PokeInfo("619", "Mienfoo", "Fighting", "None"));
        dict.Add("620", new PokeInfo("620", "Mienshao", "Fighting", "None"));
        dict.Add("621", new PokeInfo("621", "Druddigon", "Dragon", "None"));
        dict.Add("622", new PokeInfo("622", "Golett", "Ground", "Ghost"));
        dict.Add("623", new PokeInfo("623", "Golurk", "Ground", "Ghost"));
        dict.Add("624", new PokeInfo("624", "Pawniard", "Dark", "Steel"));
        dict.Add("625", new PokeInfo("625", "Bisharp", "Dark", "Steel"));
        dict.Add("626", new PokeInfo("626", "Bouffalant", "Normal", "None"));
        dict.Add("627", new PokeInfo("627", "Rufflet", "Normal", "Flying"));
        dict.Add("628", new PokeInfo("628", "Braviary", "Normal", "Flying"));
        dict.Add("629", new PokeInfo("629", "Vullaby", "Dark", "Flying"));
        dict.Add("630", new PokeInfo("630", "Mandibuzz", "Dark", "Flying"));
        dict.Add("631", new PokeInfo("631", "Heatmor", "Fire", "None"));
        dict.Add("632", new PokeInfo("632", "Durant", "Bug", "Steel"));
        dict.Add("633", new PokeInfo("633", "Deino", "Dark", "Dragon"));
        dict.Add("634", new PokeInfo("634", "Zweilous", "Dark", "Dragon"));
        dict.Add("635", new PokeInfo("635", "Hydreigon", "Dark", "Dragon"));
        dict.Add("636", new PokeInfo("636", "Larvesta", "Bug", "Fire"));
        dict.Add("637", new PokeInfo("637", "Volcarona", "Bug", "Fire"));
        dict.Add("638", new PokeInfo("638", "Cobalion", "Steel", "Fighting"));
        dict.Add("639", new PokeInfo("639", "Terrakion", "Rock", "Fighting"));
        dict.Add("640", new PokeInfo("640", "Virizion", "Grass", "Fighting"));
        dict.Add("641", new PokeInfo("641", "Tornadus", "Flying", "None"));
        dict.Add("642", new PokeInfo("642", "Thundurus", "Electric", "Flying"));
        dict.Add("643", new PokeInfo("643", "Reshiram", "Dragon", "Fire"));
        dict.Add("644", new PokeInfo("644", "Zekrom", "Dragon", "Electric"));
        dict.Add("645", new PokeInfo("645", "Landorus", "Ground", "Flying"));
        dict.Add("646", new PokeInfo("646", "Kyurem", "Dragon", "Ice"));
        dict.Add("647", new PokeInfo("647", "Keldeo", "Water", "Fighting"));
        dict.Add("648", new PokeInfo("648", "Meloetta", "Normal", "Psychic"));
        dict.Add("648alola", new PokeInfo("648alola", "Meloetta", "Normal", "Fighting"));
        dict.Add("649", new PokeInfo("649", "Genesect", "Bug", "Steel"));
        dict.Add("650", new PokeInfo("650", "Chespin", "Grass", "None"));
        dict.Add("651", new PokeInfo("651", "Quilladin", "Grass", "None"));
        dict.Add("652", new PokeInfo("652", "Chesnaught", "Grass", "Fighting"));
        dict.Add("653", new PokeInfo("653", "Fennekin", "Fire", "None"));
        dict.Add("654", new PokeInfo("654", "Braixen", "Fire", "None"));
        dict.Add("655", new PokeInfo("655", "Delphox", "Fire", "Psychic"));
        dict.Add("656", new PokeInfo("656", "Froakie", "Water", "None"));
        dict.Add("657", new PokeInfo("657", "Frogadier", "Water", "None"));
        dict.Add("658", new PokeInfo("658", "Greninja", "Water", "Dark"));
        dict.Add("659", new PokeInfo("659", "Bunnelby", "Normal", "None"));
        dict.Add("660", new PokeInfo("660", "Diggersby", "Normal", "Ground"));
        dict.Add("661", new PokeInfo("661", "Fletchling", "Normal", "Flying"));
        dict.Add("662", new PokeInfo("662", "Fletchinder", "Fire", "Flying"));
        dict.Add("663", new PokeInfo("663", "Talonflame", "Fire", "Flying"));
        dict.Add("664", new PokeInfo("664", "Scatterbug", "Bug", "None"));
        dict.Add("665", new PokeInfo("665", "Spewpa", "Bug", "None"));
        dict.Add("666", new PokeInfo("666", "Vivillon", "Bug", "Flying"));
        dict.Add("667", new PokeInfo("667", "Litleo", "Fire", "Normal"));
        dict.Add("668", new PokeInfo("668", "Pyroar", "Fire", "Normal"));
        dict.Add("669", new PokeInfo("669", "Flabébé", "Fairy", "None"));
        dict.Add("670", new PokeInfo("670", "Floette", "Fairy", "None"));
        dict.Add("671", new PokeInfo("671", "Florges", "Fairy", "None"));
        dict.Add("672", new PokeInfo("672", "Skiddo", "Grass", "None"));
        dict.Add("673", new PokeInfo("673", "Gogoat", "Grass", "None"));
        dict.Add("674", new PokeInfo("674", "Pancham", "Fighting", "None"));
        dict.Add("675", new PokeInfo("675", "Pangoro", "Fighting", "Dark"));
        dict.Add("676", new PokeInfo("676", "Furfrou", "Normal", "None"));
        dict.Add("677", new PokeInfo("677", "Espurr", "Psychic", "None"));
        dict.Add("678", new PokeInfo("678", "Meowstic", "Psychic", "None"));
        dict.Add("679", new PokeInfo("679", "Honedge", "Steel", "Ghost"));
        dict.Add("680", new PokeInfo("680", "Doublade", "Steel", "Ghost"));
        dict.Add("681", new PokeInfo("681", "Aegislash", "Steel", "Ghost"));
        dict.Add("682", new PokeInfo("682", "Spritzee", "Fairy", "None"));
        dict.Add("683", new PokeInfo("683", "Aromatisse", "Fairy", "None"));
        dict.Add("684", new PokeInfo("684", "Swirlix", "Fairy", "None"));
        dict.Add("685", new PokeInfo("685", "Slurpuff", "Fairy", "None"));
        dict.Add("686", new PokeInfo("686", "Inkay", "Dark", "Psychic"));
        dict.Add("687", new PokeInfo("687", "Malamar", "Dark", "Psychic"));
        dict.Add("688", new PokeInfo("688", "Binacle", "Rock", "Water"));
        dict.Add("689", new PokeInfo("689", "Barbaracle", "Rock", "Water"));
        dict.Add("690", new PokeInfo("690", "Skrelp", "Poison", "Water"));
        dict.Add("691", new PokeInfo("691", "Dragalge", "Poison", "Dragon"));
        dict.Add("692", new PokeInfo("692", "Clauncher", "Water", "None"));
        dict.Add("693", new PokeInfo("693", "Clawitzer", "Water", "None"));
        dict.Add("694", new PokeInfo("694", "Helioptile", "Electric", "Normal"));
        dict.Add("695", new PokeInfo("695", "Heliolisk", "Electric", "Normal"));
        dict.Add("696", new PokeInfo("696", "Tyrunt", "Rock", "Dragon"));
        dict.Add("697", new PokeInfo("697", "Tyrantrum", "Rock", "Dragon"));
        dict.Add("698", new PokeInfo("698", "Amaura", "Rock", "Ice"));
        dict.Add("699", new PokeInfo("699", "Aurorus", "Rock", "Ice"));
        dict.Add("700", new PokeInfo("700", "Sylveon", "Fairy", "None"));
        dict.Add("701", new PokeInfo("701", "Hawlucha", "Fighting", "Flying"));
        dict.Add("702", new PokeInfo("702", "Dedenne", "Electric", "Fairy"));
        dict.Add("703", new PokeInfo("703", "Carbink", "Rock", "Fairy"));
        dict.Add("704", new PokeInfo("704", "Goomy", "Dragon", "None"));
        dict.Add("705", new PokeInfo("705", "Sliggoo", "Dragon", "None"));
        dict.Add("706", new PokeInfo("706", "Goodra", "Dragon", "None"));
        dict.Add("707", new PokeInfo("707", "Klefki", "Steel", "Fairy"));
        dict.Add("708", new PokeInfo("708", "Phantump", "Ghost", "Grass"));
        dict.Add("709", new PokeInfo("709", "Trevenant", "Ghost", "Grass"));
        dict.Add("710", new PokeInfo("710", "Pumpkaboo", "Ghost", "Grass"));
        dict.Add("711", new PokeInfo("711", "Gourgeist", "Ghost", "Grass"));
        dict.Add("712", new PokeInfo("712", "Bergmite", "Ice", "None"));
        dict.Add("713", new PokeInfo("713", "Avalugg", "Ice", "None"));
        dict.Add("714", new PokeInfo("714", "Noibat", "Flying", "Dragon"));
        dict.Add("715", new PokeInfo("715", "Noivern", "Flying", "Dragon"));
        dict.Add("716", new PokeInfo("716", "Xerneas", "Fairy", "None"));
        dict.Add("717", new PokeInfo("717", "Yveltal", "Dark", "Flying"));
        dict.Add("718", new PokeInfo("718", "Zygarde", "Dragon", "Ground"));
        dict.Add("719", new PokeInfo("719", "Diancie", "Rock", "Fairy"));
        dict.Add("720", new PokeInfo("720", "Hoopa", "Psychic", "Ghost"));
        dict.Add("720alola", new PokeInfo("720alola", "Hoopa", "Psychic", "Dark"));
        dict.Add("721", new PokeInfo("721", "Volcanion", "Fire", "Water"));
        dict.Add("722", new PokeInfo("722", "Rowlet", "Grass", "Flying"));
        dict.Add("723", new PokeInfo("723", "Dartrix", "Grass", "Flying"));
        dict.Add("724", new PokeInfo("724", "Decidueye", "Grass", "Ghost"));
        dict.Add("725", new PokeInfo("725", "Litten", "Fire", "None"));
        dict.Add("726", new PokeInfo("726", "Torracat", "Fire", "None"));
        dict.Add("727", new PokeInfo("727", "Incineroar", "Fire", "Dark"));
        dict.Add("728", new PokeInfo("728", "Popplio", "Water", "None"));
        dict.Add("729", new PokeInfo("729", "Brionne", "Water", "None"));
        dict.Add("730", new PokeInfo("730", "Primarina", "Water", "Fairy"));
        dict.Add("731", new PokeInfo("731", "Pikipek", "Normal", "Flying"));
        dict.Add("732", new PokeInfo("732", "Trumbeak", "Normal", "Flying"));
        dict.Add("733", new PokeInfo("733", "Toucannon", "Normal", "Flying"));
        dict.Add("734", new PokeInfo("734", "Yungoos", "Normal", "None"));
        dict.Add("735", new PokeInfo("735", "Gumshoos", "Normal", "None"));
        dict.Add("736", new PokeInfo("736", "Grubbin", "Bug", "None"));
        dict.Add("737", new PokeInfo("737", "Charjabug", "Bug", "Electric"));
        dict.Add("738", new PokeInfo("738", "Vikavolt", "Bug", "Electric"));
        dict.Add("739", new PokeInfo("739", "Crabrawler", "Fighting", "None"));
        dict.Add("740", new PokeInfo("740", "Crabominable", "Fighting", "Ice"));
        dict.Add("741", new PokeInfo("741", "Oricorio", "Fire", "Flying"));
        dict.Add("741alola", new PokeInfo("741alola", "Oricorio", "Electric", "Flying"));
        dict.Add("741alola1", new PokeInfo("741alola", "Oricorio", "Psychic", "Flying"));
        dict.Add("741alola2", new PokeInfo("741alola", "Oricorio", "Ghost", "Flying"));
        dict.Add("742", new PokeInfo("742", "Cutiefly", "Bug", "Fairy"));
        dict.Add("743", new PokeInfo("743", "Ribombee", "Bug", "Fairy"));
        dict.Add("744", new PokeInfo("744", "Rockruff", "Rock", "None"));
        dict.Add("745", new PokeInfo("745", "Lycanroc", "Rock", "None"));
        dict.Add("746", new PokeInfo("746", "Wishiwashi", "Water", "None"));
        dict.Add("747", new PokeInfo("747", "Mareanie", "Poison", "Water"));
        dict.Add("748", new PokeInfo("748", "Toxapex", "Poison", "Water"));
        dict.Add("749", new PokeInfo("749", "Mudbray", "Ground", "None"));
        dict.Add("750", new PokeInfo("750", "Mudsdale", "Ground", "None"));
        dict.Add("751", new PokeInfo("751", "Dewpider", "Water", "Bug"));
        dict.Add("752", new PokeInfo("752", "Araquanid", "Water", "Bug"));
        dict.Add("753", new PokeInfo("753", "Fomantis", "Grass", "None"));
        dict.Add("754", new PokeInfo("754", "Lurantis", "Grass", "None"));
        dict.Add("755", new PokeInfo("755", "Morelull", "Grass", "Fairy"));
        dict.Add("756", new PokeInfo("756", "Shiinotic", "Grass", "Fairy"));
        dict.Add("757", new PokeInfo("757", "Salandit", "Poison", "Fire"));
        dict.Add("758", new PokeInfo("758", "Salazzle", "Poison", "Fire"));
        dict.Add("759", new PokeInfo("759", "Stufful", "Normal", "Fighting"));
        dict.Add("760", new PokeInfo("760", "Bewear", "Normal", "Fighting"));
        dict.Add("761", new PokeInfo("761", "Bounsweet", "Grass", "None"));
        dict.Add("762", new PokeInfo("762", "Steenee", "Grass", "None"));
        dict.Add("763", new PokeInfo("763", "Tsareena", "Grass", "None"));
        dict.Add("764", new PokeInfo("764", "Comfey", "Fairy", "None"));
        dict.Add("765", new PokeInfo("765", "Oranguru", "Normal", "Psychic"));
        dict.Add("766", new PokeInfo("766", "Passimian", "Fighting", "None"));
        dict.Add("767", new PokeInfo("767", "Wimpod", "Bug", "Water"));
        dict.Add("768", new PokeInfo("768", "Golisopod", "Bug", "Water"));
        dict.Add("769", new PokeInfo("769", "Sandygast", "Ghost", "Ground"));
        dict.Add("770", new PokeInfo("770", "Palossand", "Ghost", "Ground"));
        dict.Add("771", new PokeInfo("771", "Pyukumuku", "Water", "None"));
        dict.Add("772", new PokeInfo("772", "Type: Null", "Normal", "None"));
        dict.Add("773", new PokeInfo("773", "Silvally", "Normal", "None"));
        dict.Add("774", new PokeInfo("774", "Minior", "Rock", "Flying"));
        dict.Add("775", new PokeInfo("775", "Komala", "Normal", "None"));
        dict.Add("776", new PokeInfo("776", "Turtonator", "Fire", "Dragon"));
        dict.Add("777", new PokeInfo("777", "Togedemaru", "Electric", "Steel"));
        dict.Add("778", new PokeInfo("778", "Mimikyu", "Ghost", "Fairy"));
        dict.Add("779", new PokeInfo("779", "Bruxish", "Water", "Psychic"));
        dict.Add("780", new PokeInfo("780", "Drampa", "Normal", "Dragon"));
        dict.Add("781", new PokeInfo("781", "Dhelmise", "Ghost", "Grass"));
        dict.Add("782", new PokeInfo("782", "Jangmo-o", "Dragon", "None"));
        dict.Add("783", new PokeInfo("783", "Hakamo-o", "Dragon", "Fighting"));
        dict.Add("784", new PokeInfo("784", "Kommo-o", "Dragon", "Fighting"));
        dict.Add("785", new PokeInfo("785", "Tapu Koko", "Electric", "Fairy"));
        dict.Add("786", new PokeInfo("786", "Tapu Lele", "Psychic", "Fairy"));
        dict.Add("787", new PokeInfo("787", "Tapu Bulu", "Grass", "Fairy"));
        dict.Add("788", new PokeInfo("788", "Tapu Fini", "Water", "Fairy"));
        dict.Add("789", new PokeInfo("789", "Cosmog", "Psychic", "None"));
        dict.Add("790", new PokeInfo("790", "Cosmoem", "Psychic", "None"));
        dict.Add("791", new PokeInfo("791", "Solgaleo", "Psychic", "Steel"));
        dict.Add("792", new PokeInfo("792", "Lunala", "Psychic", "Ghost"));
        dict.Add("793", new PokeInfo("793", "Nihilego", "Rock", "Poison"));
        dict.Add("794", new PokeInfo("794", "Buzzwole", "Bug", "Fighting"));
        dict.Add("795", new PokeInfo("795", "Pheromosa", "Bug", "Fighting"));
        dict.Add("796", new PokeInfo("796", "Xurkitree", "Electric", "None"));
        dict.Add("797", new PokeInfo("797", "Celesteela", "Steel", "Flying"));
        dict.Add("798", new PokeInfo("798", "Kartana", "Grass", "Steel"));
        dict.Add("799", new PokeInfo("799", "Guzzlord", "Dark", "Dragon"));
        dict.Add("800", new PokeInfo("800", "Necrozma", "Psychic", "None"));
        dict.Add("801", new PokeInfo("801", "Magearna", "Steel", "Fairy"));
        dict.Add("802", new PokeInfo("802", "Marshadow", "Fighting", "Ghost"));
        dict.Add("803", new PokeInfo("803", "Poipole", "Poison", "None"));
        dict.Add("804", new PokeInfo("804", "Naganadel", "Poison", "Dragon"));
        dict.Add("805", new PokeInfo("805", "Stakataka", "Rock", "Steel"));
        dict.Add("806", new PokeInfo("806", "Blacephalon", "Fire", "Ghost"));
        dict.Add("807", new PokeInfo("807", "Zeraora", "Electric", "None"));
        dict.Add("808", new PokeInfo("808", "Meltan", "Steel", "None"));
        dict.Add("809", new PokeInfo("809", "Melmetal", "Steel", "None"));
    }
}
